-- SeaTunnel Control Plane PostgreSQL schema
-- Usage:
--   psql -h 127.0.0.1 -p 5360 -U postgres -d seatunnel_control_plane -f sql/init.sql

CREATE TABLE IF NOT EXISTS users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(64)  NOT NULL,
    password_hash   varchar(255) NOT NULL,
    role            varchar(16)  NOT NULL DEFAULT 'user',
    is_enabled      boolean      NOT NULL DEFAULT true,
    created_at      timestamp    NOT NULL,
    updated_at      timestamp    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username);

CREATE TABLE IF NOT EXISTS sessions (
    id          varchar(64) PRIMARY KEY,
    user_id     bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at  timestamp   NOT NULL,
    created_at  timestamp   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS app_settings (
    key         varchar(128) PRIMARY KEY,
    value       text         NOT NULL,
    updated_at  timestamp    NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL,
    description     text,
    config_format   varchar(16)  NOT NULL DEFAULT 'hocon',
    config_content  text         NOT NULL,
    default_job_name varchar(255),
    created_at      timestamp    NOT NULL,
    updated_at      timestamp    NOT NULL,
    last_run_at     timestamp,
    last_job_id     varchar(255),
    last_job_status varchar(255) NOT NULL DEFAULT 'IDLE',
    last_error_msg  text,
    is_enabled      boolean      NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_tasks_updated_at ON tasks (updated_at);

CREATE TABLE IF NOT EXISTS task_runs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     bigint       NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    job_id      varchar(255) NOT NULL,
    job_name    varchar(255),
    status      varchar(255) NOT NULL DEFAULT 'SUBMITTED',
    error_msg   text,
    started_at  timestamp    NOT NULL,
    finished_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_task_runs_task_id ON task_runs (task_id, started_at);

CREATE TABLE IF NOT EXISTS task_schedules (
    task_id              bigint PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
    enabled              boolean      NOT NULL DEFAULT false,
    cron_expr            varchar(255) NOT NULL DEFAULT '0 9 * * *',
    cron_config          text         NOT NULL,
    timezone             varchar(255) NOT NULL DEFAULT 'Asia/Shanghai',
    next_run_at          timestamp,
    last_trigger_at      timestamp,
    last_trigger_status  varchar(255),
    last_trigger_error   text,
    updated_at           timestamp    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_task_schedules_enabled ON task_schedules (enabled, next_run_at);
